### ISSUE TITLE
Does not appear to run

### ISSUE THREAD

**Issue by ghost** [selcuk/ozb#1]
Tried to run with no arguments, same error in Ubuntu 18.04 (WSL) and Pop OS (Proper install). Followed the steps to make the file executable.

`$ ozb`
`/usr/local/bin/ozb: line 6: syntax error near unexpected token newline`
`/usr/local/bin/ozb: line 6: <!DOCTYPE html>`

Running with sudo.

`$ sudo ozb`
`/usr/local/bin/ozb: 7: Syntax error: newline unexpected`

**Comment by selcuk** [comment]
You seem to have downloaded the Github web page instead of the script. Try [this link](https://raw.githubusercontent.com/selcuk/ozb/master/ozb) and click File > Save.

**Comment by ghost** [comment]
Managed to get it going, seems to work okay. Would just be curious to know how the tags are setup as it seems to miss things. Fun idea though, I like it.
